name: CI - PyKenp

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: x64

    - name: Instalar dependências
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Rodar testes
      run: |
        pytest

    # 🔹 Step do Telegram
    - name: Enviar alerta no Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "🚀 Novo commit/merge na branch ${{ github.ref }}!"
